CREATE USER cali WITH PASSWORD 'Astros2022';
GRANT CONNECT ON DATABASE padres TO cali;
GRANT USAGE ON SCHEMA aveloxis_data TO cali;
GRANT USAGE ON SCHEMA spdx TO cali;
GRANT USAGE ON SCHEMA aveloxis_ops TO cali;
GRANT SELECT ON ALL TABLES IN SCHEMA aveloxis_data TO cali;
GRANT SELECT ON ALL TABLES IN SCHEMA spdx TO cali; 
ALTER DEFAULT PRIVILEGES IN SCHEMA aveloxis_data
GRANT SELECT ON TABLES TO cali;