// SPDX-FileCopyrightText: 2026 Sean Goggins, University of Missouri, Derek Howard
// SPDX-License-Identifier: MIT

// v0.27.133 C2 — parent→child edge extraction fixtures. The C1 parsers
// read most of this data and DISCARDED it (package-lock's per-entry
// dependency maps were decoded into structs and thrown away); these
// fixtures pin that every edge-bearing format now yields edges, that
// yarn-berry (previously ZERO entries, silently) parses fully, and
// that the edge-less Category C formats stay honestly empty.
package collector

import (
	"testing"
)

func edgeSet(edges []LockfileEdge) map[string]string {
	m := map[string]string{}
	for _, e := range edges {
		m[e.ParentName+">"+e.ChildName] = e.Constraint
	}
	return m
}

func TestPackageLockV2Edges(t *testing.T) {
	data := []byte(`{
		"lockfileVersion": 3,
		"packages": {
			"": {"dependencies": {"express": "^4.0.0"}},
			"node_modules/express": {"version": "4.18.2", "dependencies": {"body-parser": "1.20.1"}},
			"node_modules/body-parser": {"version": "1.20.1"}
		}
	}`)
	parsed, err := parsePackageLockJSON(data)
	if err != nil {
		t.Fatal(err)
	}
	es := edgeSet(parsed.Edges)
	if es["express>body-parser"] != "1.20.1" {
		t.Errorf("want express>body-parser edge with its constraint, got %v", es)
	}
}

func TestPackageLockV1Edges(t *testing.T) {
	data := []byte(`{
		"dependencies": {
			"a": {"version": "1.0.0", "dependencies": {"b": {"version": "2.0.0"}}}
		}
	}`)
	parsed, err := parsePackageLockJSON(data)
	if err != nil {
		t.Fatal(err)
	}
	if _, ok := edgeSet(parsed.Edges)["a>b"]; !ok {
		t.Errorf("v1 nested walk must record the parent edge, got %v", parsed.Edges)
	}
}

func TestYarnV1Edges(t *testing.T) {
	data := []byte(`# yarn lockfile v1

express@^4.0.0:
  version "4.18.2"
  resolved "https://registry.yarnpkg.com/express/-/express-4.18.2.tgz"
  dependencies:
    body-parser "1.20.1"
    "@types/node" "^18.0.0"

body-parser@1.20.1:
  version "1.20.1"
`)
	parsed, err := parseYarnLock(data)
	if err != nil {
		t.Fatal(err)
	}
	if len(parsed.Entries) != 2 {
		t.Fatalf("want 2 entries, got %+v", parsed.Entries)
	}
	es := edgeSet(parsed.Edges)
	if es["express>body-parser"] != "1.20.1" || es["express>@types/node"] != "^18.0.0" {
		t.Errorf("yarn v1 dependencies blocks must become edges (quoted scoped names included), got %v", es)
	}
}

// The 36-file fleet cohort that parsed to ZERO entries before
// v0.27.133: yarn berry writes `version: X` (YAML colon) where the v1
// scanner matched only `version "X"`.
func TestYarnBerryParsesEntriesDirectAndEdges(t *testing.T) {
	data := []byte(`# This file is generated by running "yarn install" inside your project.

__metadata:
  version: 8
  cacheKey: 10

"myproject@workspace:.":
  version: 0.0.0-use.local
  resolution: "myproject@workspace:."
  dependencies:
    express: "npm:^4.0.0"
  languageName: unknown
  linkType: soft

"express@npm:^4.0.0":
  version: 4.18.2
  resolution: "express@npm:4.18.2"
  dependencies:
    body-parser: "npm:1.20.1"
  languageName: node
  linkType: hard

"body-parser@npm:1.20.1":
  version: 1.20.1
  resolution: "body-parser@npm:1.20.1"
  languageName: node
  linkType: hard

"@scope/util@npm:^2.0.0":
  version: 2.1.0
  resolution: "@scope/util@npm:2.1.0"
  languageName: node
  linkType: hard
`)
	parsed, err := parseYarnLock(data)
	if err != nil {
		t.Fatal(err)
	}
	byName := map[string]LockfileEntry{}
	for _, e := range parsed.Entries {
		byName[e.Name] = e
	}
	if len(parsed.Entries) != 3 {
		t.Fatalf("want 3 package entries (workspace + __metadata excluded), got %+v", parsed.Entries)
	}
	if byName["express"].Version != "4.18.2" || byName["@scope/util"].Version != "2.1.0" {
		t.Errorf("berry versions mis-parsed: %+v", byName)
	}
	if !parsed.DirectKnown || !byName["express"].Direct || byName["body-parser"].Direct {
		t.Errorf("the workspace entry's deps are the DIRECT set: express direct, body-parser transitive; got directKnown=%v %+v", parsed.DirectKnown, byName)
	}
	es := edgeSet(parsed.Edges)
	if es["express>body-parser"] != "npm:1.20.1" {
		t.Errorf("berry dependencies blocks must become edges, got %v", es)
	}
	if _, ok := es["myproject>express"]; ok {
		t.Error("the workspace entry is the direct SET, not an edge parent")
	}
}

func TestPnpmV9SnapshotEdges(t *testing.T) {
	data := []byte(`lockfileVersion: '9.0'

importers:
  .:
    dependencies:
      express:
        specifier: ^4.0.0
        version: 4.18.2

packages:
  express@4.18.2:
    resolution: {integrity: sha512-x}
  body-parser@1.20.1:
    resolution: {integrity: sha512-y}

snapshots:
  express@4.18.2:
    dependencies:
      body-parser: 1.20.1
  body-parser@1.20.1: {}
`)
	parsed, err := parsePnpmLock(data)
	if err != nil {
		t.Fatal(err)
	}
	if es := edgeSet(parsed.Edges); es["express>body-parser"] != "1.20.1" {
		t.Errorf("pnpm v9 snapshots must yield edges (resolved-version constraints), got %v", es)
	}
}

func TestBunLockEdges(t *testing.T) {
	data := []byte(`{
		"lockfileVersion": 1,
		"workspaces": {"": {"dependencies": {"express": "^4.0.0"}}},
		"packages": {
			"express": ["express@4.19.2", "", { "dependencies": { "body-parser": "1.20.2" } }, "sha512-abc"],
			"body-parser": ["body-parser@1.20.2", "", {}, "sha512-def"]
		}
	}`)
	parsed, err := parseBunLock(data)
	if err != nil {
		t.Fatal(err)
	}
	if es := edgeSet(parsed.Edges); es["express>body-parser"] != "1.20.2" {
		t.Errorf("bun tuple[2] dependencies must become edges, got %v", es)
	}
}

func TestPoetryDependencySubtableEdges(t *testing.T) {
	data := []byte(`
[[package]]
name = "flask"
version = "2.3.0"

[package.dependencies]
werkzeug = ">=2.3.3"
click = {version = ">=8.1.3", optional = false}

[[package]]
name = "werkzeug"
version = "2.3.7"
`)
	parsed, err := parsePoetryStyleTOML(data)
	if err != nil {
		t.Fatal(err)
	}
	if len(parsed.Entries) != 2 {
		t.Fatalf("the deps sub-table must not terminate the package block: %+v", parsed.Entries)
	}
	es := edgeSet(parsed.Edges)
	if es["flask>werkzeug"] != ">=2.3.3" || es["flask>click"] != ">=8.1.3" {
		t.Errorf("poetry [package.dependencies] must become edges (inline-table version extracted), got %v", es)
	}
}

func TestCargoLockDependencyArrayEdges(t *testing.T) {
	data := []byte(`
[[package]]
name = "serde"
version = "1.0.190"
dependencies = [
 "serde_derive",
]

[[package]]
name = "serde_derive"
version = "1.0.190"
dependencies = [
 "proc-macro2 1.0.69",
]
`)
	parsed, err := parsePoetryStyleTOML(data)
	if err != nil {
		t.Fatal(err)
	}
	if len(parsed.Entries) != 2 {
		t.Fatalf("want both packages, got %+v", parsed.Entries)
	}
	es := edgeSet(parsed.Edges)
	if _, ok := es["serde>serde_derive"]; !ok {
		t.Errorf("Cargo dependency arrays must become edges, got %v", es)
	}
	if es["serde_derive>proc-macro2"] != "1.0.69" {
		t.Errorf("Cargo 'name version' array elements must split, got %v", es)
	}
}

func TestGemfileLockChildEdges(t *testing.T) {
	data := []byte(`GEM
  remote: https://rubygems.org/
  specs:
    rails (7.0.8)
      actionpack (= 7.0.8)
      activesupport (= 7.0.8)
    actionpack (7.0.8)

DEPENDENCIES
  rails
`)
	parsed, err := parseGemfileLock(data)
	if err != nil {
		t.Fatal(err)
	}
	es := edgeSet(parsed.Edges)
	if es["rails>actionpack"] != "= 7.0.8" {
		t.Errorf("6-space constraint lines must become edges of the preceding spec, got %v", es)
	}
}

func TestComposerLockRequireEdges(t *testing.T) {
	data := []byte(`{
		"packages": [
			{"name": "monolog/monolog", "version": "3.5.0",
			 "require": {"php": ">=8.1", "psr/log": "^2.0 || ^3.0"}}
		],
		"packages-dev": []
	}`)
	parsed, err := parseComposerLock(data)
	if err != nil {
		t.Fatal(err)
	}
	es := edgeSet(parsed.Edges)
	if es["monolog/monolog>psr/log"] != "^2.0 || ^3.0" {
		t.Errorf("composer require maps must become edges, got %v", es)
	}
	if _, ok := es["monolog/monolog>php"]; ok {
		t.Error("platform pseudo-packages (php, ext-*) are not composer packages — no edge")
	}
}

func TestMixLockDepTupleEdges(t *testing.T) {
	data := []byte(`%{
  "phoenix": {:hex, :phoenix, "1.7.10", "hash", [:mix], [{:castore, ">= 0.0.0", [hex: :castore, repo: "hexpm", optional: false]}, {:plug, "~> 1.14", [hex: :plug, repo: "hexpm", optional: false]}], "hexpm", "hash2"},
  "castore": {:hex, :castore, "1.0.4", "hash", [:mix], [], "hexpm", "hash2"},
}
`)
	parsed, err := parseMixLock(data)
	if err != nil {
		t.Fatal(err)
	}
	es := edgeSet(parsed.Edges)
	if es["phoenix>castore"] != ">= 0.0.0" || es["phoenix>plug"] != "~> 1.14" {
		t.Errorf("mix.lock dep tuples must become edges, got %v", es)
	}
	if len(edgeSet(parsed.Edges)) != 2 {
		t.Errorf("the entry's own {:hex head must not match as a dep tuple, got %v", parsed.Edges)
	}
}

func TestDotnetPackagesLockEdges(t *testing.T) {
	data := []byte(`{
		"version": 1,
		"dependencies": {
			"net8.0": {
				"Serilog": {"type": "Direct", "resolved": "3.1.1",
					"dependencies": {"Serilog.Sinks.Console": "5.0.0"}},
				"Serilog.Sinks.Console": {"type": "Transitive", "resolved": "5.0.0"}
			}
		}
	}`)
	parsed, err := parseDotnetPackagesLock(data)
	if err != nil {
		t.Fatal(err)
	}
	if es := edgeSet(parsed.Edges); es["Serilog>Serilog.Sinks.Console"] != "5.0.0" {
		t.Errorf("nuget per-package dependencies must become edges, got %v", es)
	}
}

// Category C — formats whose files carry NO parent→child data:
// attribution is honestly impossible and edges stay empty.
func TestEdgelessFormatsStayEmpty(t *testing.T) {
	cases := []struct {
		kind string
		data string
	}{
		{"Pipfile.lock", `{"default": {"flask": {"version": "==2.3.0"}}, "develop": {}}`},
		{"pubspec.lock", "packages:\n  http:\n    dependency: \"direct main\"\n    version: \"1.1.0\"\n"},
		{"gradle.lockfile", "org.slf4j:slf4j-api:2.0.9=runtimeClasspath\n"},
	}
	for _, c := range cases {
		res, err := ParseLockfile(c.kind, []byte(c.data))
		if err != nil {
			t.Fatalf("%s: %v", c.kind, err)
		}
		if len(res.Edges) != 0 {
			t.Errorf("%s carries no edge data — parsed edges %v are fabricated", c.kind, res.Edges)
		}
		if len(res.Entries) == 0 {
			t.Errorf("%s: entries lost in the signature conversion", c.kind)
		}
	}
}
